-- Run in Snowflake UI or SnowSQL
-- Account: PLHVTTI-MWC64694
-- URL: PLHVTTI-MWC64694.snowflakecomputing.com
-- User: YASEEN / Role: ACCOUNTADMIN / Warehouse: COMPUTE_WH

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- Auto-suspend warehouse when idle (saves credits)
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE COMPUTE_WH SET AUTO_RESUME = TRUE;

-- Database and schemas
CREATE DATABASE IF NOT EXISTS HACKATHON_IOT;

CREATE SCHEMA IF NOT EXISTS HACKATHON_IOT.RAW;
CREATE SCHEMA IF NOT EXISTS HACKATHON_IOT.CLEAN;
CREATE SCHEMA IF NOT EXISTS HACKATHON_IOT.ANALYTICS;

-- Bronze table (Snowflake Kafka Connector writes here as VARIANT)
CREATE TABLE IF NOT EXISTS HACKATHON_IOT.RAW.IOT_EVENTS (
    RECORD_CONTENT  VARIANT,
    RECORD_METADATA VARIANT,
    INSERTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Verify
SHOW DATABASES LIKE 'HACKATHON_IOT';
SHOW SCHEMAS IN DATABASE HACKATHON_IOT;
SELECT COUNT(*) FROM HACKATHON_IOT.RAW.IOT_EVENTS;
